global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets:
          - gateway:4000

  - job_name: platform
    static_configs:
      - targets:
          - platform:9000

  - job_name: proxy
    static_configs:
      - targets:
          - proxy:8080
